apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: rec
spec:
  # Add fields here
  nodes: 3
  redisEnterpriseNodeResources:
    limits:
      cpu: "1000m"
      memory: 2Gi
    requests:
      cpu: "1000m"
      memory: 2Gi
